// Mirrors the backend `Language` enum
// (almonium-be .../analyzer/translator/model/enums/Language.java). Keep the two in
// step when a language is added there. Hermes has no Intl.DisplayNames, so the
// names live here rather than being asked of the runtime.
const names: Record<string, string> = {
  AF: 'Afrikaans',
  SQ: 'Albanian',
  AM: 'Amharic',
  AR: 'Arabic',
  HY: 'Armenian',
  AS: 'Assamese',
  AY: 'Aymara',
  AZ: 'Azerbaijani',
  BM: 'Bambara',
  EU: 'Basque',
  BE: 'Belarusian',
  BN: 'Bengali',
  BHO: 'Bhojpuri',
  BS: 'Bosnian',
  BG: 'Bulgarian',
  CA: 'Catalan',
  CEB: 'Cebuano',
  ZH: 'Chinese',
  CO: 'Corsican',
  HR: 'Croatian',
  CS: 'Czech',
  DA: 'Danish',
  DV: 'Dhivehi',
  DOI: 'Dogri',
  NL: 'Dutch',
  EN: 'English',
  EO: 'Esperanto',
  ET: 'Estonian',
  EE: 'Ewe',
  FIL: 'Filipino',
  FI: 'Finnish',
  FR: 'French',
  FY: 'Frisian',
  GL: 'Galician',
  KA: 'Georgian',
  DE: 'German',
  EL: 'Greek',
  GN: 'Guarani',
  GU: 'Gujarati',
  HT: 'Haitian Creole',
  HA: 'Hausa',
  HAW: 'Hawaiian',
  HE: 'Hebrew',
  HI: 'Hindi',
  HMN: 'Hmong',
  HU: 'Hungarian',
  IS: 'Icelandic',
  IG: 'Igbo',
  ILO: 'Ilocano',
  ID: 'Indonesian',
  GA: 'Irish',
  IT: 'Italian',
  JA: 'Japanese',
  JV: 'Javanese',
  KN: 'Kannada',
  KK: 'Kazakh',
  KM: 'Khmer',
  RW: 'Kinyarwanda',
  GOM: 'Konkani',
  KO: 'Korean',
  KRI: 'Krio',
  KU: 'Kurdish',
  CKB: 'Kurdish (Sorani)',
  KY: 'Kyrgyz',
  LO: 'Lao',
  LA: 'Latin',
  LV: 'Latvian',
  LN: 'Lingala',
  LT: 'Lithuanian',
  LG: 'Luganda',
  LB: 'Luxembourgish',
  MK: 'Macedonian',
  MAI: 'Maithili',
  MG: 'Malagasy',
  MS: 'Malay',
  ML: 'Malayalam',
  MT: 'Maltese',
  MI: 'Maori',
  MR: 'Marathi',
  LUS: 'Mizo',
  MN: 'Mongolian',
  MY: 'Burmese',
  NE: 'Nepali',
  NO: 'Norwegian',
  NY: 'Chichewa',
  OR: 'Odia',
  OM: 'Oromo',
  PS: 'Pashto',
  FA: 'Persian',
  PL: 'Polish',
  PT: 'Portuguese',
  PA: 'Punjabi',
  QU: 'Quechua',
  RO: 'Romanian',
  RU: 'Russian',
  SM: 'Samoan',
  SA: 'Sanskrit',
  GD: 'Scots Gaelic',
  NSO: 'Sepedi',
  SR: 'Serbian',
  ST: 'Sesotho',
  SN: 'Shona',
  SD: 'Sindhi',
  SI: 'Sinhala',
  SK: 'Slovak',
  SL: 'Slovenian',
  SO: 'Somali',
  ES: 'Spanish',
  SU: 'Sundanese',
  SW: 'Swahili',
  SV: 'Swedish',
  TL: 'Tagalog',
  TG: 'Tajik',
  TA: 'Tamil',
  TT: 'Tatar',
  TE: 'Telugu',
  TH: 'Thai',
  TI: 'Tigrinya',
  TS: 'Tsonga',
  TR: 'Turkish',
  TK: 'Turkmen',
  AK: 'Twi',
  UK: 'Ukrainian',
  UR: 'Urdu',
  UG: 'Uyghur',
  UZ: 'Uzbek',
  VI: 'Vietnamese',
  CY: 'Welsh',
  XH: 'Xhosa',
  YI: 'Yiddish',
  YO: 'Yoruba',
  ZU: 'Zulu',
};

/**
 * Full English name for a backend language code. Tolerates lowercase and a
 * region subtag (`pt-BR`, `zh_TW`) so book metadata resolves too. Unknown codes
 * come back upper-cased so the screen still shows something legible.
 */
export function languageName(code: string) {
  if (!code) return '';
  const base = code.split(/[-_]/)[0].toUpperCase();
  return names[base] || code.toUpperCase();
}

export function sortLanguages(codes: string[]) {
  return [...codes].sort((a, b) => languageName(a).localeCompare(languageName(b)));
}
