import { msg, t } from './i18n';

// Mirrors the backend `Language` enum
// (almonium-be .../analyzer/translator/model/enums/Language.java). Keep the two in
// step when a language is added there. Hermes has no Intl.DisplayNames, so the
// names live here rather than being asked of the runtime.
const names: Record<string, string> = {
  AF: msg('Afrikaans'),
  SQ: msg('Albanian'),
  AM: msg('Amharic'),
  AR: msg('Arabic'),
  HY: msg('Armenian'),
  AS: msg('Assamese'),
  AY: msg('Aymara'),
  AZ: msg('Azerbaijani'),
  BM: msg('Bambara'),
  EU: msg('Basque'),
  BE: msg('Belarusian'),
  BN: msg('Bengali'),
  BHO: msg('Bhojpuri'),
  BS: msg('Bosnian'),
  BG: msg('Bulgarian'),
  CA: msg('Catalan'),
  CEB: msg('Cebuano'),
  ZH: msg('Chinese'),
  CO: msg('Corsican'),
  HR: msg('Croatian'),
  CS: msg('Czech'),
  DA: msg('Danish'),
  DV: msg('Dhivehi'),
  DOI: msg('Dogri'),
  NL: msg('Dutch'),
  EN: msg('English'),
  EO: msg('Esperanto'),
  ET: msg('Estonian'),
  EE: msg('Ewe'),
  FIL: msg('Filipino'),
  FI: msg('Finnish'),
  FR: msg('French'),
  FY: msg('Frisian'),
  GL: msg('Galician'),
  KA: msg('Georgian'),
  DE: msg('German'),
  EL: msg('Greek'),
  GN: msg('Guarani'),
  GU: msg('Gujarati'),
  HT: msg('Haitian Creole'),
  HA: msg('Hausa'),
  HAW: msg('Hawaiian'),
  HE: msg('Hebrew'),
  HI: msg('Hindi'),
  HMN: msg('Hmong'),
  HU: msg('Hungarian'),
  IS: msg('Icelandic'),
  IG: msg('Igbo'),
  ILO: msg('Ilocano'),
  ID: msg('Indonesian'),
  GA: msg('Irish'),
  IT: msg('Italian'),
  JA: msg('Japanese'),
  JV: msg('Javanese'),
  KN: msg('Kannada'),
  KK: msg('Kazakh'),
  KM: msg('Khmer'),
  RW: msg('Kinyarwanda'),
  GOM: msg('Konkani'),
  KO: msg('Korean'),
  KRI: msg('Krio'),
  KU: msg('Kurdish'),
  CKB: msg('Kurdish (Sorani)'),
  KY: msg('Kyrgyz'),
  LO: msg('Lao'),
  LA: msg('Latin'),
  LV: msg('Latvian'),
  LN: msg('Lingala'),
  LT: msg('Lithuanian'),
  LG: msg('Luganda'),
  LB: msg('Luxembourgish'),
  MK: msg('Macedonian'),
  MAI: msg('Maithili'),
  MG: msg('Malagasy'),
  MS: msg('Malay'),
  ML: msg('Malayalam'),
  MT: msg('Maltese'),
  MI: msg('Maori'),
  MR: msg('Marathi'),
  LUS: msg('Mizo'),
  MN: msg('Mongolian'),
  MY: msg('Burmese'),
  NE: msg('Nepali'),
  NO: msg('Norwegian'),
  NY: msg('Chichewa'),
  OR: msg('Odia'),
  OM: msg('Oromo'),
  PS: msg('Pashto'),
  FA: msg('Persian'),
  PL: msg('Polish'),
  PT: msg('Portuguese'),
  PA: msg('Punjabi'),
  QU: msg('Quechua'),
  RO: msg('Romanian'),
  RU: msg('Russian'),
  SM: msg('Samoan'),
  SA: msg('Sanskrit'),
  GD: msg('Scots Gaelic'),
  NSO: msg('Sepedi'),
  SR: msg('Serbian'),
  ST: msg('Sesotho'),
  SN: msg('Shona'),
  SD: msg('Sindhi'),
  SI: msg('Sinhala'),
  SK: msg('Slovak'),
  SL: msg('Slovenian'),
  SO: msg('Somali'),
  ES: msg('Spanish'),
  SU: msg('Sundanese'),
  SW: msg('Swahili'),
  SV: msg('Swedish'),
  TL: msg('Tagalog'),
  TG: msg('Tajik'),
  TA: msg('Tamil'),
  TT: msg('Tatar'),
  TE: msg('Telugu'),
  TH: msg('Thai'),
  TI: msg('Tigrinya'),
  TS: msg('Tsonga'),
  TR: msg('Turkish'),
  TK: msg('Turkmen'),
  AK: msg('Twi'),
  UK: msg('Ukrainian'),
  UR: msg('Urdu'),
  UG: msg('Uyghur'),
  UZ: msg('Uzbek'),
  VI: msg('Vietnamese'),
  CY: msg('Welsh'),
  XH: msg('Xhosa'),
  YI: msg('Yiddish'),
  YO: msg('Yoruba'),
  ZU: msg('Zulu'),
};

/**
 * Full name for a backend language code, in the interface language. Tolerates lowercase and a
 * region subtag (`pt-BR`, `zh_TW`) so book metadata resolves too. Unknown codes
 * come back upper-cased so the screen still shows something legible.
 */
export function languageName(code: string) {
  if (!code) return '';
  const base = code.split(/[-_]/)[0].toUpperCase();
  const name = names[base];
  return name ? t(name) : code.toUpperCase();
}

export function sortLanguages(codes: string[]) {
  return [...codes].sort((a, b) => languageName(a).localeCompare(languageName(b)));
}
